package com.example.daotest;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "SIM_BEAN".
 */
@Entity
public class SimBean {

    @Id
    private Integer pid;
    private Long mId;
    private Double mTracffic;

    @Generated
    public SimBean() {
    }

    public SimBean(Integer pid) {
        this.pid = pid;
    }

    @Generated
    public SimBean(Integer pid, Long mId, Double mTracffic) {
        this.pid = pid;
        this.mId = mId;
        this.mTracffic = mTracffic;
    }

    public Integer getPid() {
        return pid;
    }

    public void setPid(Integer pid) {
        this.pid = pid;
    }

    public Long getMId() {
        return mId;
    }

    public void setMId(Long mId) {
        this.mId = mId;
    }

    public Double getMTracffic() {
        return mTracffic;
    }

    public void setMTracffic(Double mTracffic) {
        this.mTracffic = mTracffic;
    }

}
